name: SotaAndRadio
version: '${project.version}'
main: ru.yoricya.privat.sota.sotaandradio.SotaAndRadio
api-version: 1.19
commands:
  newSota:
    description: Новая Станция
    usage: /newSota <Имя> <Частота или Тип> <Мощность> <Коментарий>
    permission: sotaradio.newSota
