name: SotaAndRadio
version: '${project.version}'
main: ru.yoricya.privat.sota.sotaandradio.SotaAndRadio
api-version: 1.19
commands:
  newSota:
    description: Новая сота
    usage: /newSota <Имя> <Частота или Тип> <Мощность> <Коментарий>
    permission: sotaradio.newSota
  delSota:
    description: Удалить соту
    usage: /delSota <ID>
    permission: sotaradio.delSota
  nearSota:
    description: Соты поблизости
    usage: /nearSota
  userParams:
    description: Параметры Пользователя
    usage: /paramUser <Параметр> <Значение>
  myOperator:
    description: Установить оператора
    usage: /myOperator <Имя>
  helpSota:
    description: Инфо
    usage: /helpSota
  setPhone:
    description: setPhone
    usage: /setPhone <Оператор> <Макс сеть> <Имя телефона>
  infoPhone:
    description: infoPhone
    usage: /infoPhone
  delPhone:
    description: delPhone
    usage: /delPhone
  newMark:
    description: New Marker
    usage: /newMark
  delMark:
    description: Remove Marker
    usage: /delMark
  gm:
    description: Gamemode
    usage: /gm <Mode>
  setHome:
    description: Gamemode
    usage: /gm <Mode>
  tptoHome:
    description: Gamemode
    usage: /gm <Mode>
  delHome:
    description: Gamemode
    usage: /gm <Mode>
permissions:
  sotaradio.*:
    description: Все права
  sotaradio.delSota:
    description: Право на удаление соты
  sotaradio.newSota:
    description: Право на создание соты

